### PR TITLE
SSH handler/listener plugins

### PR DESCRIPTION
**Pull request by abhinavsingh**

### CODE REVIEW

**Comment by abhinavsingh** [comment]
@webknjaz Wondering if we need to update `flake8` version for `proxy.py` repository too.   Unsure what happened yesterday, but:

1) I merged couple of PRs yesterday, all good
2) But since late last night we started getting `pre-commit` errors on this PR
3) Locally all pre-commit hooks seem to pass

So I figured may be some upstream dep has changed, though unsure which one

```
- repo: https://github.com/PyCQA/flake8.git
  rev: 3.9.2
  hooks:
  - id: flake8
    language_version: python3
    additional_dependencies:
    - flake8-2020 >= 1.6.0
    - flake8-docstrings >= 1.5.0
    - flake8-pytest-style >= 1.2.2
    - wemake-python-styleguide >= 0.16.1
```

I investigated above packages and none seem to have released a new version yesterday.

Unsure if `pre-commit` image itself has changed sometime yesterday resulting pre-commit failures.

**Comment by abhinavsingh** [comment]
> @webknjaz Wondering if we need to update `flake8` version for `proxy.py` repository too. Unsure what happened yesterday, but:
> 
> 1. I merged couple of PRs yesterday, all good
> 2. But since late last night we started getting `pre-commit` errors on this PR
> 3. Locally all pre-commit hooks seem to pass
> 
> So I figured may be some upstream dep has changed, though unsure which one
> 
> ```
> - repo: https://github.com/PyCQA/flake8.git
>   rev: 3.9.2
>   hooks:
>   - id: flake8
>     language_version: python3
>     additional_dependencies:
>     - flake8-2020 >= 1.6.0
>     - flake8-docstrings >= 1.5.0
>     - flake8-pytest-style >= 1.2.2
>     - wemake-python-styleguide >= 0.16.1
> ```
> 
> I investigated above packages and none seem to have released a new version yesterday.
> 
> Unsure if `pre-commit` image itself has changed sometime yesterday resulting pre-commit failures.

Screenshot 2024-04-24 at 2 47 51 PM

Another hint I got that something has changed, because `pre-commit` started sending these suggestions, which frankly looks non-sensical.

**Comment by abhinavsingh** [comment]
Indeed, can verify this by comparing hash of `pre-commit` image:

1) Pre-commit run from `develop` (HEAD) is using an image from 2023 https://results.pre-commit.ci/run/github/12228178/1713880307.Z5PTirFHQc-YfBNGH5yqJA
2) Since last night, pre-commit started using a newer image, which uses Python 3.12 :(. https://results.pre-commit.ci/run/github/12228178/1713923336.SpNwhUIiRc-9jaXw_TljCg

Hence the unexpected errors IIUC

**Comment by webknjaz** [comment]
@abhinavsingh yes, I'm getting this in other projects too. It looks like the pre-commit.ci service updated their container images and now default to using Python 3.12 there. I'm trying to figure out what updates to make elsewhere but hitting problems with other plugin incompatibilities like https://github.com/wemake-services/wemake-python-styleguide/issues/2933 so I don't have a final solution yet. The workaround of pinning the Python version seems like a reasonable stopgap for now.

**Pull request merged**
