### PR TITLE
Add CLI usage for pki.py and update Makefile

### PR DESCRIPTION
**Pull request by abhinavsingh**
See #234 and #251 for background

### CODE REVIEW

**Comment by abhinavsingh** [comment]
jFYI @JohnnySheppard @Benouare

**Comment by abhinavsingh** [comment]
@JohnnySheppard @Benouare

I updated `Makefile` to use `pki.py` now, can you folks give it a try and verify.  Thank you!!!

**Comment by abhinavsingh** [comment]
See https://github.com/abhinavsingh/proxy.py/tree/pki#cli-usage for CLI usage.

**Comment by JohnnySheppard** [comment]
> @JohnnySheppard @Benouare
> 
> I updated `Makefile` to use `pki.py` now, can you folks give it a try and verify. Thank you!!!

Thanks for sorting this so quickly. I'll try it as soon as I can (which will probably be Wednesday evening).

Thanks again.

**Comment by Benouare** [comment]
Just tried it, and it works. 
Still have the issue with the OSError when wrapping client / SEC_ERROR_REUSED_ISSUER_AND_SERIAL, but its working better than using certs generated by the "classic" openssl calls.

**Pull request merged**
