### PR TITLE
Build docker container for all linux target architectures`386`, `amd64`, `arm/v6`, `arm/v7`, `arm64/v8`, `ppc64le`, `s390x`

### LINKED ISSUE #768: [Docker] Unable to launch container for `linux/arm64`
**Describe the bug**
Built the docker file on `linux/arm64` architecture from the `master` branch
After launching a container, it crashes with following error

```
Traceback (most recent call last):
  File "/usr/local/bin/proxy", line 5, in <module>
    from proxy import entry_point
ModuleNotFoundError: No module named 'proxy'
```

**To Reproduce**
1. docker build -t <image> . 
2. launch container using the above image
4. check pod logs for above error

**Expected behavior**
Container should successfully run

### PR DESCRIPTION
**Pull request by abhinavsingh**
Fixes #768

### CODE REVIEW

**Comment by abhinavsingh** [comment]
Well this ran into https://github.com/abhinavsingh/proxy.py/runs/4318230566?check_suite_focus=true for `arm64` and unsure how to fix it :(.   Issue is `lsb_release` is likely expecting to use `python 2.7` but we are running the task from `python 3+` environment, resulting into failure.  Wth.

```
#11 [linux/arm64 4/5] RUN pip install --upgrade pip &&   pip install   --no-index   --find-links file:///   proxy.py &&   rm *.whl
#11 13.39 ERROR: Exception:
#11 13.39 Traceback (most recent call last):
#11 13.39   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
#11 13.39     status = self.run(options, args)
#11 13.39   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
#11 13.39     return func(self, options, args)
#11 13.39   File "/usr/local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 266, in run
#11 13.39     session = self.get_default_session(options)
#11 13.39   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 74, in get_default_session
#11 13.39     self._session = self.enter_context(self._build_session(options))
#11 13.39   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 88, in _build_session
#11 13.39     session = PipSession(
#11 13.39   File "/usr/local/lib/python3.10/site-packages/pip/_internal/network/session.py", line 289, in __init__
#11 13.39     self.headers["User-Agent"] = user_agent()
#11 13.39   File "/usr/local/lib/python3.10/site-packages/pip/_internal/network/session.py", line 132, in user_agent
#11 13.39     linux_distribution = distro.linux_distribution()  # type: ignore
#11 13.39   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/distro.py", line 125, in linux_distribution
#11 13.39     return _distro.linux_distribution(full_distribution_name)
#11 13.39   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/distro.py", line 681, in linux_distribution
#11 13.39     self.version(),
#11 13.39   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/distro.py", line 741, in version
#11 13.39     self.lsb_release_attr('release'),
#11 13.39   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
#11 13.39     return self._lsb_release_info.get(attribute, '')
#11 13.39   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/distro.py", line 556, in __get__
#11 13.39     ret = obj.__dict__[self._fname] = self._f(obj)
#11 13.39   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
#11 13.39     stdout = subprocess.check_output(cmd, stderr=devnull)
#11 13.39   File "/usr/local/lib/python3.10/subprocess.py", line 420, in check_output
#11 13.39     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#11 13.39   File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
#11 13.39     raise CalledProcessError(retcode, process.args,
#11 13.39 subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
```

**Comment by abhinavsingh** [comment]
Also see

- https://github.com/actions/virtual-environments/issues/2552#issuecomment-870862549

**Comment by rennokki** [comment]
Wait, how were you able to dockerize ARM arch in non-ARM OS with Github Actions? I'm still struggling to fix https://github.com/soketi/soketi/pull/154 but the installation process is super slow. It takes tens of minutes to build ARM images.

**Comment by rennokki** [comment]
Ignore that brainfart, Multiarch FTW. 🤯

**Comment by abhinavsingh** [comment]
> Ignore that brainfart, Multiarch FTW. 🤯

Yep `multiarch` was the key, took me some googling to discover myself and so many commits (see above) to get it right in GHA.  I wish GHA had a local only version

**Comment by abhinavsingh** [comment]
FWIW, at some point `proxy.py` will also add support for `windows/amd` and `windows/arm`.   It's possible.  But above workflow alone left me exhausted, so didn't jump to that in this PR :D

**Pull request merged**
