### PR TITLE
Support plugins defined as inner classes

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Support referencing the following plugin class by name and by type:

```python
class Outer:
    class MyHttpProxyPlugin(HttpProxyPlugin):
        # ...
```

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
Hm, I may need some insights on what have failed since:

```
Unable to find qualified name for module: check.py

tests/test_main.py
```

is there for me on unmodified `develop` as well

**Comment by abhinavsingh** [comment]
> Hm, I may need some insights on what have failed since:
> 
> ```
> Unable to find qualified name for module: check.py
> 
> tests/test_main.py
> ```
> 
> is there for me on unmodified `develop` as well

Thank you @alexey-pelykh for this PR.   These are possibly broken due to updated lint toolkit (in this case flake8 I suppose).  At times upstream changes starts to show up as new lint errors in our repo :(.  I'll address this in a separate PR and re-run/review this PR sometime morrow.   Thanks again.

**Comment by abhinavsingh** [comment]
@alexey-pelykh I am fixing the lint issues via https://github.com/abhinavsingh/proxy.py/pull/1321 , we should be able to get going on this PR thereafter.   Meanwhile, could you add a few lines about capabilities that this PR adds to the `Loading Plugins` section.   This will allow others to also discover this magic :)  https://github.com/abhinavsingh/proxy.py#loading-plugins

**Comment by abhinavsingh** [comment]
@alexey-pelykh All looks good.   Thank you again for your PR and included tests 🙏. Merging, we can update doc in a separate PR effort.

**Review by abhinavsingh — COMMENTED** [review]
LGTM

**Pull request merged**
