### PR TITLE
Integrate showing unreleased changelog draft

### PR DESCRIPTION
**Pull request by webknjaz**
Preview: https://proxypy--873.org.readthedocs.build/en/873/changelog/#changelog

### CODE REVIEW

**Comment by webknjaz** [comment]
@abhinavsingh I think the change note is not important here, it can be skipped.

**Comment by webknjaz** [comment]
@abhinavsingh and the docker job failures seem unrelated/flaky.

**Comment by abhinavsingh** [comment]
@webknjaz Yes docker build failures are caused by upstream changed in `buildx` and deps, ref https://github.com/docker/buildx/issues/850

Probably, we can merge with broken CI.  We have other PRs pending too.  At-least we don't publish Docker containers from CI, so should be safe (given that the tests are passing)

**Comment by webknjaz** [comment]
> Probably, we can merge with broken CI. We have other PRs pending too. At-least we don't publish Docker containers from CI, so should be safe (given that the tests are passing)

Yep, also, if you want you could temporarily add `docker` to the `allowed-failures` input in `re-actors/alls-green` so it unblocks the branch protection while it's broken upstream.

**Comment by webknjaz** [comment]
@abhinavsingh also, after you merge this, think of which changes you'd like to be present in the changelog for 2.4.0 and add respective files for them retroactively (I guess you could add all files in the same PR). Now that you'll be able to see the next version draft, it'll be easier to decide if it looks fine before attempting to release. Just don't forget to follow the writing style principles laid out in https://github.com/abhinavsingh/proxy.py/tree/develop/docs/changelog-fragments.d#adding-change-notes-with-your-prs so that it'd be consistent and useful for the intended audience in general.

**Comment by abhinavsingh** [comment]
Totally.  I have skipped adding change notes in past few PRs, where I could have.

As you pointed out, I am planning to add batch change notes in a single PR.

May be with time we must start enforcing change notes wherever applicable.  Need to try it out soon 😃

**Pull request merged**
