### PR TITLE
Publish to TestPyPI from the release request jobs

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by webknjaz** [comment]
@abhinavsingh try making `2.4.0a2` after this to confirm the fix.

**Comment by abhinavsingh** [comment]
jFYI https://github.com/abhinavsingh/proxy.py/actions/runs/1513306752 in progress now

**Comment by webknjaz** [comment]
> jFYI [abhinavsingh/proxy.py/actions/runs/1513306752](https://github.com/abhinavsingh/proxy.py/actions/runs/1513306752) in progress now

Great, it also created https://github.com/abhinavsingh/proxy.py/releases/tag/v2.4.0a2

**Comment by abhinavsingh** [comment]
Correct, I guess good to make an `rc` from master, finally a stable

**Comment by webknjaz** [comment]
Yep, unless you wanted to wait for the release notes management improvements, that is.

**Comment by abhinavsingh** [comment]
I guess we can stick with `rc` until we get few other things in?  I am myself looking into docker releases, want to get that in with 2.4.0.

**Pull request merged**
