### PR TITLE
python3 support

### PR DESCRIPTION
**Pull request by podhmo**

### CODE REVIEW

**Comment by abhinavsingh** [comment]
@podhmo Thanks for this PR. I haven't had a chance to go through it yet but looks good from top look. I will be addressing this back shortly over the weekend.

**Comment by abhinavsingh** [comment]
@podhmo This PR moves `proxy.py` away from "Distributed as a single file" philosophy. WDYT about putting it back together into a single file?

**Comment by podhmo** [comment]
@abhinavsingh ok. i only want to running proxy.py  in python3.x. so, just follow it.

**Comment by podhmo** [comment]
oh, sorry. 
> Distributed as a single file module

**Pull request merged**
