### PR TITLE
`--plugin` and `--plugins` flags doesn't work consistently together

### PR DESCRIPTION
**Pull request by sakurai-youhei**
**Issue** Custom flags in my own plugin won't be discovered with `--plugins`. Workaround is using `--plugin` instead.

- Doesn't work: `proxy --plugins my.own.Plugin --custom-flag spam`
- Does work: `proxy --plugin my.own.Plugin --custom-flag spam`

**Singular v.s. Plural** `--plugin` sounds consistent but `--plugins` is being used intentionally.

**Proposal** Fix the issue without removing the original singular `--plugin`.

### CODE REVIEW

**Comment by abhinavsingh** [comment]
@sakurai-youhei Thank you for the PR.  Indeed plurals should work too.  However, tests seems to be failing.  Example: https://github.com/abhinavsingh/proxy.py/pull/553/checks?check_run_id=2595396247. Can you please take a look at them.  You can run them locally and debug too.  Thank you!!!

**Comment by sakurai-youhei** [comment]
@abhinavsingh Thank you for pointing it out; It's my fault as I didn't imagine such small change breaks anything.

Now that I makes the change with writing small tests. Hope they would be compliant with existing manners and pass the checks. :)

**Comment by abhinavsingh** [comment]
@sakurai-youhei My apologies, but I highly recommend you setup pre-commit hooks locally , see https://github.com/abhinavsingh/proxy.py#setup-pre-commit-hook. You can also manually just run `make` before pushing to remote, this will run all git workflows on your local system.

This will avoid any unnecessary failures which you can catch locally first.  Looks like we have a lint error next.

Screen Shot 2021-05-17 at 7 14 30 PM

**Comment by sakurai-youhei** [comment]
@abhinavsingh I am sorry for my laziness again. I set it up and confirmed no errors locally.

**Comment by sakurai-youhei** [comment]
@abhinavsingh Let me re-work it as I didn't check the change with older version of Python...

**Comment by abhinavsingh** [comment]
@sakurai-youhei This should be fixed after

- #725

**Comment by sakurai-youhei** [comment]
Thanks!

**Pull request closed without merging**
